py_binary(
    name = "part-one",
    srcs = ["part-one.py"],
    data = ["input.txt"],
    main = "part-one.py",
)

cc_binary(
    name = "part-two",
    srcs = ["part-two.cpp"],
    data = ["input.txt"],
)
