py_binary(
    name = "part-one",
    srcs = ["part-one.py"],
    data = ["input.txt"],
    main = "part-one.py",
)

py_binary(
    name = "part-two",
    srcs = ["part-two.py"],
    data = ["input.txt"],
    main = "part-two.py",
)
