py_binary(
    name = "part-one",
    srcs = ["part-one.py"],
    main = "part-one.py",
    data = ["input.txt"],
)

cc_binary(
    name = "part-two",
    srcs = ["part-two.cpp"],
    data = ["input.txt"]
)
